### ISSUE TITLE
win8.1上运行start.vbs后无效果

### ISSUE THREAD

**Issue by faywong** [ladder1984/updateHosts#1]
![hosts](https://cloud.githubusercontent.com/assets/1934627/5889450/a71adb98-a462-11e4-8a2d-65b2545b134e.png)
如图所示，运行后没有反馈是否成功。
之后在浏览器中输入google域的网址，无法成功访问。

**Comment by ladder1984** [comment]
因为是设计成开机启动静默执行，所以没有反馈。你打开C:\Windows\System32\drivers\etc\hosts文件，看看有没有更新成功？

**Comment by faywong** [comment]
后来等了一会儿。貌似是好了。谢谢。
