### ISSUE TITLE
win10出现错误

### ISSUE THREAD

**Issue by mckatscu** [ladder1984/updateHosts#2]
2015-10-24 12:04:18.596000
function:backup_hosts
error:[Errno 13] Permission denied: 'C:\Windows\System32\drivers\etc\backup_hosts_original_by_updateHosts'

**Comment by ladder1984** [comment]
试试这样：Windows用户可能需要授予程序管理员权限：右击python27.exe，选中“属性”，在“兼容性”里勾选“以管理员身份运行此程序”
